In [1]:
import pandas as pd
import numpy as np

## 1. What is the version of NumPy you installed?

In [2]:
np.__version__

'1.16.4'

## 2. What's the version of Pandas?

In [3]:
pd.__version__

'0.24.2'

In [4]:
cars = pd.read_csv('cars.csv')
cars.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

## 3. What is the average price of BMW?

In [5]:
cars.groupby('Make')['MSRP'].mean()

Make
Acura            3.488759e+04
Alfa Romeo       6.160000e+04
Aston Martin     1.979104e+05
Audi             5.345211e+04
BMW              6.154676e+04
Bentley          2.471693e+05
Bugatti          1.757224e+06
Buick            2.820661e+04
Cadillac         5.623132e+04
Chevrolet        2.835039e+04
Chrysler         2.672296e+04
Dodge            2.239006e+04
FIAT             2.267024e+04
Ferrari          2.382188e+05
Ford             2.739927e+04
GMC              3.049330e+04
Genesis          4.661667e+04
HUMMER           3.646441e+04
Honda            2.667434e+04
Hyundai          2.459704e+04
Infiniti         4.239421e+04
Kia              2.531017e+04
Lamborghini      3.315673e+05
Land Rover       6.782322e+04
Lexus            4.754907e+04
Lincoln          4.283983e+04
Lotus            6.918828e+04
Maserati         1.142077e+05
Maybach          5.462219e+05
Mazda            2.003938e+04
McLaren          2.398050e+05
Mercedes-Benz    7.147623e+04
Mitsubishi       2.124054e+04
Nissa

## 4. Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [6]:
(cars.query('Year >= 2015')['Engine HP']).isna().sum()

51

## 5

* Calculate the average "Engine HP" in the dataset.
* Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
* Now, calcualte the average of "Engine HP" again.
* Has it changed?

Round both means before answering this questions. You can use the round function for that

In [7]:
hp_mean_before = cars['Engine HP'].mean()
round(hp_mean_before)

249

In [8]:
na_filled = cars['Engine HP'].fillna(value=cars['Engine HP'].mean())


In [9]:
engine_hp = cars['Engine HP']

In [10]:
before_mean = engine_hp.mean()
before_mean

249.38607007176023

In [11]:
filled = engine_hp.fillna(value=engine_hp.mean())
after_mean = filled.mean()
after_mean

249.38607007176

In [12]:
print(round(before_mean))
print(round(after_mean))

249
249


## 6

* Select all the "Rolls-Royce" cars from the dataset.
* Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
* Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
* Get the underlying NumPy array. Let's call it X.
* Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
* Invert XTX.
* What's the sum of all the elements of the result?

Hint: if the result is negative, re-read the task one more time

In [13]:
rr = cars.query('Make == "Rolls-Royce"')
rr.head()

Make            Model  Year             Engine Fuel Type  \
2921  Rolls-Royce         Corniche  2001  premium unleaded (required)   
3505  Rolls-Royce             Dawn  2016  premium unleaded (required)   
5275  Rolls-Royce  Ghost Series II  2015  premium unleaded (required)   
5276  Rolls-Royce  Ghost Series II  2015  premium unleaded (required)   
5277  Rolls-Royce  Ghost Series II  2016  premium unleaded (required)   

      Engine HP  Engine Cylinders Transmission Type     Driven_Wheels  \
2921      325.0               8.0         AUTOMATIC  rear wheel drive   
3505      563.0              12.0         AUTOMATIC  rear wheel drive   
5275      563.0              12.0         AUTOMATIC  rear wheel drive   
5276      563.0              12.0         AUTOMATIC  rear wheel drive   
5277      563.0              12.0         AUTOMATIC  rear wheel drive   

      Number of Doors                 Market Category Vehicle Size  \
2921              2.0                   Exotic,Luxury        Large   
3505              2.0  Exotic,Luxury,High-Performance        Large   
5275              4.0       Exotic,Luxury,Performance        Large   
5276              4.0       Exotic,Luxury,Performance        Large   
5277              4.0       Exotic,Luxury,Performance        Large   

     Vehicle Style  highway MPG  city mpg  Popularity    MSRP  
2921   Convertible           15        10          86  359990  
3505   Convertible           19        12          86  335000  
5275         Sedan           21        13          86  286750  
5276         Sedan           21        13          86  319400  
5277         Sedan           21        13          86  295850

In [14]:
rr_data = rr[['Engine HP', 'Engine Cylinders', 'highway MPG']]
rr_data

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0           19
7559       453.0              12.0           19
7560       453.0              12.0           19
7561       453.0              12.0           19
7562       453.0              12.0           19
7563       453.0              12.0           19
7564       453.0              12.0           19
9431       322.0              12.0           15
9432       322.0              12.0           15
11448      624.0              12.0           21
11449      624.0              12.0           21
11450      624.0              12.0           21

In [15]:
new_rr = rr_data.drop_duplicates()
new_rr

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [16]:
X = new_rr.to_numpy()
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [17]:
XTX = np.dot(X.T, X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [18]:
inv_sum = np.linalg.inv(XTX).sum()
inv_sum

0.032212320677486195

In [19]:
inv = np.linalg.inv(XTX)
inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

## 7


* Create an array `y` with values `[1000, 1100, 900, 1200, 1000, 850, 1300]`.
* Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
* What's the value of the first element of w?.


In [20]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

In [21]:
inv.shape

(3, 3)

In [22]:
X.T.shape

(3, 7)

In [26]:
w = np.dot(inv, X.T)
np.dot(w, y)[0]

0.19989598183186175